Pharma/Models/Medicine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pharma.Models
{
    public class Medicine
    {
        [Key]
        public int Medicine_Id { get; set; }
        public string Medicine_Name { get; set; }
        public string Medicine_Type     { get; set; }
        
        public string Medicine_Reg_Number { get; set; }

        public double Medicine_Size { get; set; }
        public string Medicine_Unit     { get; set; }
        public string Medicine_Form { get; set; }
        public string Medicine_Qty { get; set; }
        public double Medicine_Price { get; set; }
        public DateTime Medicine_Expiry_Date { get; set; }


    }
}

Pharma/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pharma.Data;
using Pharma.Migrations;
using Pharma.Models;

namespace Pharma.Controllers
{
    public class MedicinesController : Controller
    {
        private readonly AuthDbContext _context;

        public MedicinesController(AuthDbContext context)
        {
            _context = context;
        }

        // GET: Medicines
        [Authorize]
        public async Task<IActionResult> Index(string medicinetype, string searchString)
        {
            IQueryable<string> medicinequery = from m in _context.Medicine
                                               orderby m.Medicine_Type
                                               select m.Medicine_Type;
            var medicine = from m in _context.Medicine
                           select m;
            if(!string.IsNullOrEmpty(searchString))
            {
                medicine = medicine.Where(s => s.Medicine_Name.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(medicinetype))
            {
                medicine = medicine.Where(x => x.Medicine_Type == medicinetype);
            }
            var MedicineTypeList = new MedicineListModel
            {
                MedicineList = new SelectList(await medicinequery.Distinct().ToListAsync()),
                Medicines = await medicine.ToListAsync()
            };
            /* return _context.Medicine != null ? 
                         View(await _context.Medicine.ToListAsync()) :
                         Problem("Entity set 'MedicineContext.Medicine'  is null.");
       */
            return View(MedicineTypeList);
        }

        // GET: Medicines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Medicine == null)
            {
                return NotFound();
            }

            var medicine = await _context.Medicine
                .FirstOrDefaultAsync(m => m.Medicine_Id == id);
            if (medicine == null)
            {
                return NotFound();
            }

            return View(medicine);
        }

        // GET: Medicines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Medicine_Id,Medicine_Name,Medicine_Type,Medicine_Reg_Number,Medicine_Size,Medicine_Unit,Medicine_Form,Medicine_Qty,Medicine_Price,Medicine_Expiry_Date")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicine);
        }

        // GET: Medicines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Medicine == null)
            {
                return NotFound();
            }

            var medicine = await _context.Medicine.FindAsync(id);
            if (medicine == null)
            {
                return NotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Medicine_Id,Medicine_Name,Medicine_Type,Medicine_Reg_Number,Medicine_Size,Medicine_Unit,Medicine_Form,Medicine_Qty,Medicine_Price,Medicine_Expiry_Date")] Medicine medicine)
        {
            if (id != medicine.Medicine_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicineExists(medicine.Medicine_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicine);
        }

        // GET: Medicines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Medicine == null)
            {
                return NotFound();
            }

            var medicine = await _context.Medicine
                .FirstOrDefaultAsync(m => m.Medicine_Id == id);
            if (medicine == null)
            {
                return NotFound();
            }

            return View(medicine);
        }

        // POST: Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Medicine == null)
            {
                return Problem("Entity set 'MedicineContext.Medicine'  is null.");
            }
            var medicine = await _context.Medicine.FindAsync(id);
            if (medicine != null)
            {
                _context.Medicine.Remove(medicine);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicineExists(int id)
        {
          return (_context.Medicine?.Any(e => e.Medicine_Id == id)).GetValueOrDefault();
        }
    }
}

Pharma/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pharma.Migrations;
using Pharma.Models;
using Pharma.Data;
using Microsoft.Data.SqlClient;
using System.Data;

namespace Pharma.Controllers
{
    public class RequestsController : Controller
    {
        private readonly AuthDbContext _context;

        public RequestsController(AuthDbContext context)
        {
            _context = context;
        }
       
        // GET: Requests
        public async Task<IActionResult> Index()
        {
        var RequestContext = _context.Request.Include(o=> o.Medicine);
            /*  return _context.Request != null ? 
                          View(await _context.Request.ToListAsync()) :
                          Problem("Entity set 'RequestContext.Request'  is null.");
           */ 
            return View(await RequestContext.ToListAsync());
       
        }

        // GET: Requests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Request == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .Include(o=> o.Medicine)
                .FirstOrDefaultAsync(m => m.Request_Id == id);
            if (request == null)
            {
                return NotFound();
            }
            TempData["User"] = request.Request_User_Id;
            TempData["Medicine"] = request.Medicine.Medicine_Name;
            return View(request);
        }

        // GET: Requests/Create
        public IActionResult Create()
        {
            ViewData["Medicine_Id"] = new SelectList(_context.Medicine, "Medicine_Id", "Medicine_Name");
            return View();
            
        }
       

   

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Request_Id,Request_Date,Request_User_Id,Medicine_Id")] Request request)
        {
          //  if (ModelState.IsValid)
          //  {
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
          //  }
            ViewData["Medicine_Id"] = new SelectList(_context.Medicine, "Medicine_Id", "Medicine_Name", request.Medicine_Id);
            return View(request);
        }

        // GET: Requests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Request == null)
            {
                return NotFound();
            }

            var request = await _context.Request.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);

        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Request_Id,Request_Date,Request_User_Id,Medicine_Id")] Request request)
        {
            if (id != request.Request_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(request);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Request_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        // GET: Requests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Request == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .FirstOrDefaultAsync(m => m.Request_Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Request == null)
            {
                return Problem("Entity set 'RequestContext.Request'  is null.");
            }
            var request = await _context.Request.FindAsync(id);
            if (request != null)
            {
                _context.Request.Remove(request);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(int id)
        {
          return (_context.Request?.Any(e => e.Request_Id == id)).GetValueOrDefault();
        }
    }
}

Pharma/Views/Medicines/Create.cshtml
@model Pharma.Models.Medicine;
@using Microsoft.AspNetCore.Identity;
@using Pharma.Areas.Identity.Data;

@inject SignInManager<ApplicationUser> SignInManager;

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!SignInManager.IsSignedIn(User))
{
    Context.Response.Redirect("/Identity/Account/Login");
}
<h4>Medicine</h4>
<h6> Add Medicine Details</h6>
 <a asp-action="Index">Back to List</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Medicine_Name" class="control-label">Name</label>
                <input asp-for="Medicine_Name" class="form-control" />
                <span asp-validation-for="Medicine_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Type" class="control-label">Type</label>
                <input asp-for="Medicine_Type" class="form-control" />
                <span asp-validation-for="Medicine_Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Reg_Number"  class="control-label" > Registration Number</label>
                <input asp-for="Medicine_Reg_Number"  class="form-control"  />
                <span asp-validation-for="Medicine_Reg_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Size" class="control-label">Size</label>
                <input asp-for="Medicine_Size" class="form-control" />
                <span asp-validation-for="Medicine_Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Unit" class="control-label">Unit</label>
                <input asp-for="Medicine_Unit" class="form-control" />
                <span asp-validation-for="Medicine_Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Form" class="control-label">Form</label>
                <input asp-for="Medicine_Form" class="form-control" />
                <span asp-validation-for="Medicine_Form" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Qty" class="control-label">Quantity</label>
                <input asp-for="Medicine_Qty" class="form-control" />
                <span asp-validation-for="Medicine_Qty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Price" class="control-label">Price</label>
                <input asp-for="Medicine_Price" class="form-control" />
                <span asp-validation-for="Medicine_Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Expiry_Date" class="control-label">Expiry Date</label>
                <input asp-for="Medicine_Expiry_Date" class="form-control" />
                <span asp-validation-for="Medicine_Expiry_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pharma/Views/Medicines/Delete.cshtml
@model Pharma.Models.Medicine

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Reg_Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Reg_Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Size)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Size)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Form)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Form)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Expiry_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Expiry_Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Medicine_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Pharma/Views/Medicines/Details.cshtml
@model Pharma.Models.Medicine

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Reg_Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Reg_Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Size)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Size)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Form)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Form)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medicine_Expiry_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicine_Expiry_Date)
        </dd>
    </dl>
</div>
<div>
  <!--  <a asp-action="Edit" asp-route-id="@Model?.Medicine_Id">Edit</a> | -->
    <a asp-action="Index">Back to List</a>
</div>

Pharma/Views/Medicines/Edit.cshtml
@model Pharma.Models.Medicine

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Medicine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Medicine_Id" />
            <div class="form-group">
                <label asp-for="Medicine_Name" class="control-label"></label>
                <input asp-for="Medicine_Name" class="form-control" />
                <span asp-validation-for="Medicine_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Type" class="control-label"></label>
                <input asp-for="Medicine_Type" class="form-control" />
                <span asp-validation-for="Medicine_Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Reg_Number" class="control-label"></label>
                <input asp-for="Medicine_Reg_Number" class="form-control" />
                <span asp-validation-for="Medicine_Reg_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Size" class="control-label"></label>
                <input asp-for="Medicine_Size" class="form-control" />
                <span asp-validation-for="Medicine_Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Unit" class="control-label"></label>
                <input asp-for="Medicine_Unit" class="form-control" />
                <span asp-validation-for="Medicine_Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Form" class="control-label"></label>
                <input asp-for="Medicine_Form" class="form-control" />
                <span asp-validation-for="Medicine_Form" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Qty" class="control-label"></label>
                <input asp-for="Medicine_Qty" class="form-control" />
                <span asp-validation-for="Medicine_Qty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Price" class="control-label"></label>
                <input asp-for="Medicine_Price" class="form-control" />
                <span asp-validation-for="Medicine_Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medicine_Expiry_Date" class="control-label"></label>
                <input asp-for="Medicine_Expiry_Date" class="form-control" />
                <span asp-validation-for="Medicine_Expiry_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pharma/Views/Medicines/Index.cshtml
@model Pharma.Models.MedicineListModel
@using Microsoft.AspNetCore.Identity;
@using Pharma.Areas.Identity.Data;
@inject UserManager<ApplicationUser> UserManager;
@inject SignInManager<ApplicationUser> SignInManager;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Medicines</h1>
@if (!SignInManager.IsSignedIn(User))
{
    Context.Response.Redirect("/Identity/Account/Login");
}


    @if (User.IsInRole("Admin"))
    {
       <h3>You can add a new medicine</h3>
       <p><a asp-area="" asp-controller="Medicines" asp-action="Create" class="btn btn-primary"> Add a Medicine</a></p>
    }
    else
    {
      
        <p><a asp-area="" asp-controller="Requests" asp-action="Create" class="btn btn-primary"> Add A Medicine Request</a></p>
    }
<p>
    
</p>
<form asp-controller="Medicines" asp-action="Index" method="get">
    <p>
        Medicine Type: <select asp-for="MedicineType" asp-items="Model.MedicineList" class="form-select">
            <option value=""> All</option>
        </select>
        <br />
        Search for Medicine:  <input type="text" asp-for="searchString" class="form-control"/>
        <br />

        <input type="submit" value="Filter" class="btn btn-primary"/>
    </p>
</form>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Type)
            </th>
            @if (User.IsInRole("Admin"))
            {   
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Reg_Number)
            </th>
            }
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Unit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Form)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Qty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicines[0].Medicine_Expiry_Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Medicines) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Type)
            </td>
                @if (User.IsInRole("Admin"))
                {
                <td>
                @Html.DisplayFor(modelItem => item.Medicine_Reg_Number)
            </td>
                    
                }
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Unit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Form)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medicine_Expiry_Date)
            </td>
            <td>
                    @if (User.IsInRole("Admin"))
                    {


                        <a asp-action="Edit" asp-route-id="@item.Medicine_Id" class="btn btn-primary">Edit</a>
                    }
                    
                    <a asp-action="Details" asp-route-id="@item.Medicine_Id" class="btn btn-primary">Details</a> 
                    
                 @if (User.IsInRole("Admin"))
                    {

                        <a asp-action="Delete" asp-route-id="@item.Medicine_Id" class="btn btn-primary">Delete</a>
                    }
                </td>
        </tr>
}
    </tbody>
</table>
<br />
<br />